server:
  port: 8620
spring:
  datasource: # 数据源
    #type: com.zaxxer.hikari.HikariDataSource          # 连接池使用HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql??
    url: jdbc:mysql://8.137.39.241:4508/data-mysql?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: XSJroot123456
    hikari:
      connection-timeout: 30000        # sql超时时间 30s
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
    clickhouse:
      #driverClassName: com.clickhouse.jdbc.ClickHouseDriver
      url: 8.137.39.241:8123
      database: default
      username: default
      password: XSJroot123456
  application:
    name: datasource
  data:
    redis:
      connect-timeout: 2000
      password: XSJroot123456
      lettuce:
        pool:
          max-wait: -1ms
          max-active: 32
          max-idle: 24
          min-idle: 8
      host: 8.137.39.241
      port: 6379
logging:
  level:
    # 设置 MyBatis 的日志级别为 DEBUG
    com.baomidou.mybatisplus: DEBUG
    # 设置全局日志为debug
    com:
      study:
        datasource: DEBUG
springdoc:
  swagger-ui:
    # 自定义的文档界面访问路径。默认访问路径是/swagger-ui.html
    path: /springdoc/docs.html
    enabled: true
    # 持久化认证数据，如果设置为 true，它会保留授权数据并且不会在浏览器关闭/刷新时丢失
    persistAuthorization: true
  api-docs:
    # 修改api-docs路径
    path: /v3/api-docs
    # 开启api-docs
    enabled: true



